### ISSUE TITLE
Corrección práctica

### ISSUE THREAD

**Issue by pedroprieto** [Fernando-Albiol-Olalla/sesion3-practica#4]
Muy buenas, @Fernando-Albiol-Olalla 

Está bastante bien, aunque tienes que hacer una Pull Resuest.

Te comento cosas:
- En el apartado 5b te falta hacer un `git pull`. Por eso no te aparecen los 5 nombres
- Te ha faltado incluir en el mensaje de los commits de GitHub los textos `closes` indicando los issues a cerrar.

Buen trabajo!

**Comment by Fernando-Albiol-Olalla** [comment]
Buenas, @pedroprieto 
Ok....sabía que quizá me faltaría algo....tomare nota. A por la siguiente. Si no te molesta seguiré nombrándote como colaborador de las practicas siguientes así vamos corrigiendo sobre la marcha. Ahora toca seguir trabajando. Un saludo. Gracias.

**Comment by pedroprieto** [comment]
Todo correcto.

No hace falta que me pongas de colaborador en las siguientes prácticas: al hacer una Pull Request me llega la notificación.

Un saludo!!
